# Nombre del workflow
name: GitHub-Profile-3D-Contrib

on:
  schedule:
    # Ejecuta la acción una vez al día a las 00:00 UTC
    - cron: "0 0 * * *"
  workflow_dispatch:
    # Permite ejecutar la acción manualmente desde la pestaña Actions

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generar gráfico 3D de contribuciones # Nombre descriptivo para el job
    permissions:
      contents: write # Permisos necesarios para que GITHUB_TOKEN pueda hacer push

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4 # Actualizado a la versión v4

      - name: Generar perfil 3D de contribuciones
        # Se recomienda usar una versión específica (ej. v0.7.1) en lugar de @latest para mayor estabilidad.
        uses: yoshi389111/github-profile-3d-contrib@v0.7.1
        with:
          # Usar el GITHUB_TOKEN estándar que provee GitHub Actions.
          # Este token obtiene sus permisos del bloque 'permissions' definido a nivel del job.
          github_token: ${{ secrets.GITHUB_TOKEN }}
          username: ${{ github.repository_owner }}
          # Opciones adicionales (puedes descomentarlas y ajustarlas si quieres personalizar)
          # max_repos: 100
          # setting_json: ./conf/custom_settings.json # Si creas un archivo de configuración personalizado
          # contrib_colors: '#ff0000,#00ff00,#0000ff,#ffff00,#ff00ff' # Colores personalizados

      - name: Commit y push de los cambios
        run: |
          git config user.name "diegote22" 
          git config user.email "diegote_21_82@hotmail.com" 
          # El siguiente comando añade todos los archivos modificados y nuevos.
          # Considera ser más específico si la acción solo genera ciertos archivos (ej. git add profile-3d-contrib.svg)
          git add -A .
          git commit -m "Generar gráfico 3D de contribuciones (Automático)" || echo "No hay cambios para commitear"
          git push
